name: Stephen Lippa
favicon: null
layout_spectrum: 0.5477944256272167
typography_spectrum: 0.03727567498572171
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.04060078994370997
  lightness: 0.681853839661926
  saturation: 0.25515783089213073
  rhythmicContrast: 0.6825746928807348
purpose: []
