name: Stephen Lippa
favicon: null
layout_spectrum: 0.5477944256272167
typography_spectrum: 0.03727567498572171
title: Testing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#949590'
    - '#cccabe'
    - '#f1ead8'
    - '#484c4d'
    - '#15140f'
  brandStrength: 0.04060078994370997
  lightness: 0.681853839661926
  saturation: 0.25515783089213073
  rhythmicContrast: 0.6825746928807348
purpose: []
